urls :
  default : http://localhost:4567/
  stubbed : http://localhost:4567/
  
data :
  default : config/data/bigweb
  mobile  : config/data/mobile

page_dir:
  default : ./src/bigweb/pages
  mobile  : ./src/mobile/pages

users :
  default : config/users.yml
  stubbed : config/users.yml

stub :
  wiremock :
    jar       : standalone-2.3.1
    path      : config/stub
    port      : 8081
    root_dir  : config/stub
    verbose   : false

clients :
  default:
      browser: chrome
  firefox:
      browser: firefox
  ie:
      browser: ie
  iphone5:
    browser: chrome
    device : Apple iPhone 5
